# Generated by Django 2.2 on 2019-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notepad',
            options={'verbose_name_plural': 'notepads'},
        ),
        migrations.AlterField(
            model_name='notepad',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notepad',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
